# Do not modify this file! It was generated by `nixos-generate-config`
# and may be overwritten by future invocations.
# Make permanent system changes in /etc/nixos/configuration.nix.

{ config, lib, pkgs, modulesPath, ... }:

{
  #################################################
  ## Imports
  #################################################

  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  #################################################
  ## Boot Hardware
  #################################################

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
  ];

  boot.initrd.kernelModules = [ ];

  boot.kernelModules = [
    "kvm-amd"
  ];

  boot.extraModulePackages = [ ];

  #################################################
  ## Filesystems
  #################################################

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/436ac9dd-c4ea-42fb-90b5-51b645aec036";
    fsType = "btrfs";

    options = [
      "compress=zstd:3"
      "noatime"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/436ac9dd-c4ea-42fb-90b5-51b645aec036";
    fsType = "btrfs";

    options = [
      "subvol=home"
      "compress=zstd:3"
      "noatime"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/436ac9dd-c4ea-42fb-90b5-51b645aec036";
    fsType = "btrfs";

    options = [
      "subvol=nix"
      "compress=zstd:3"
      "noatime"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/92B8-65A4";
    fsType = "vfat";

    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  #################################################
  ## Swap
  #################################################

  swapDevices = [ ];

  #################################################
  ## Platform
  #################################################

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  #################################################
  ## CPU Microcode
  #################################################

  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}